package com.DaddyLiveHD

import android.util.Base64
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.*

class DaddyLiveHD : MainAPI() {
    override var mainUrl = "https://dlive.sx"
    override var name = "DaddyLiveHD"
    override val hasMainPage = true
    override var lang = "en"
    override val hasQuickSearch = false
    override val supportedTypes = setOf(TvType.Live)

    private val siteHeaders = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0.0.0 Safari/537.36",
        "Referer" to "https://dlive.sx/",
        "Accept" to "text/html,application/xhtml+xml"
    )

    private val channelNames = mapOf(
        "31" to "TNT Sports 1 UK",
        "32" to "TNT Sports 2 UK",
        "33" to "TNT Sports 3 UK",
        "34" to "TNT Sports 4 UK",
        "35" to "Sky Sports Football UK",
        "36" to "Sky Sports+ Plus",
        "37" to "Sky Sports Action UK",
        "38" to "Sky Sports Main Event",
        "46" to "Sky Sports Tennis UK",
        "130" to "Sky Sports Premier League",
        "60" to "Sky Sports F1 UK",
        "65" to "Sky Sports Cricket",
        "70" to "Sky Sports Golf UK",
        "366" to "Sky Sports News UK",
        "449" to "Sky Sports MIX UK",
        "554" to "Sky Sports Racing UK",
        "276" to "LaLigaTV UK",
        "230" to "DAZN 1 UK",
        "451" to "Viaplay Sports 1 UK",
        "550" to "Viaplay Sports 2 UK",
        "377" to "MUTV UK",
        "826" to "Liverpool TV (LFC TV)",
        "771" to "Premier Sports Ireland 1",
        "799" to "Premier Sports Ireland 2",
        "44" to "ESPN USA",
        "45" to "ESPN2 USA",
        "316" to "ESPNU USA",
        "288" to "ESPNews",
        "375" to "ESPN Deportes",
        "39" to "Fox Sports 1 USA",
        "758" to "Fox Sports 2 USA",
        "756" to "FOX Soccer Plus",
        "308" to "CBS Sports Network",
        "910" to "CBS Sports Golazo",
        "405" to "NFL Network",
        "667" to "NFL RedZone",
        "404" to "NBA TV USA",
        "399" to "MLB Network USA",
        "663" to "NHL Network USA",
        "318" to "GOLF Channel USA",
        "40" to "Tennis Channel",
        "425" to "BeIN SPORTS USA",
        "385" to "SEC Network USA",
        "664" to "ACC Network USA",
        "397" to "BIG TEN Network",
        "66" to "TUDN USA",
        "376" to "WWE Network",
        "757" to "Fight Network",
        "43" to "PDC TV",
        "765" to "MSG USA",
        "759" to "SportsNet New York (SNY)",
        "762" to "NESN USA",
        "763" to "YES Network USA",
        "770" to "Marquee Sports Network",
        "776" to "Chicago Sports Network",
        "777" to "NBC Sports Philadelphia",
        "921" to "Space City Home Network",
        "920" to "Root Sports Northwest",
        "982" to "Spectrum SportsNet USA",
        "764" to "Spectrum Sportsnet LA",
        "890" to "FanDuel Sports AZ",
        "891" to "FanDuel Sports Detroit",
        "892" to "FanDuel Sports Florida",
        "893" to "FanDuel Sports Great Lakes",
        "894" to "FanDuel Sports Indiana",
        "895" to "FanDuel Sports Kansas City",
        "896" to "FanDuel Sports Midwest",
        "897" to "FanDuel Sports New Orleans",
        "898" to "FanDuel Sports North",
        "899" to "FanDuel Sports Ohio",
        "900" to "FanDuel Sports Oklahoma",
        "902" to "FanDuel Sports SoCal",
        "903" to "FanDuel Sports South",
        "904" to "FanDuel Sports Southeast",
        "905" to "FanDuel Sports Sun",
        "906" to "FanDuel Sports West",
        "907" to "FanDuel Sports Wisconsin",
        "61" to "beIN Sports MENA English 1",
        "90" to "beIN Sports MENA English 2",
        "91" to "beIN Sports 1 Arabic",
        "92" to "beIN Sports 2 Arabic",
        "93" to "beIN Sports 3 Arabic",
        "94" to "beIN Sports 4 Arabic",
        "95" to "beIN Sports 5 Arabic",
        "96" to "beIN Sports 6 Arabic",
        "97" to "beIN Sports 7 Arabic",
        "98" to "beIN Sports 8 Arabic",
        "99" to "beIN Sports 9 Arabic",
        "100" to "beIN SPORTS XTRA 1",
        "494" to "beIN Sports MAX 4 France",
        "495" to "beIN Sports MAX 5 France",
        "496" to "beIN Sports MAX 6 France",
        "497" to "beIN Sports MAX 7 France",
        "498" to "beIN Sports MAX 8 France",
        "499" to "beIN Sports MAX 9 France",
        "500" to "beIN Sports MAX 10 France",
        "116" to "beIN SPORTS 1 France",
        "117" to "beIN SPORTS 2 France",
        "118" to "beIN SPORTS 3 France",
        "62" to "beIN SPORTS 1 Turkey",
        "63" to "beIN SPORTS 2 Turkey",
        "64" to "beIN SPORTS 3 Turkey",
        "67" to "beIN SPORTS 4 Turkey",
        "1010" to "bein Sports 5 Turkey",
        "578" to "BeIN Sports HD Qatar",
        "372" to "beIN SPORTS en Espanol",
        "491" to "beIN SPORTS Australia 1",
        "492" to "beIN SPORTS Australia 2",
        "493" to "beIN SPORTS Australia 3",
        "712" to "beIN Sports 1 Malaysia",
        "713" to "beIN Sports 2 Malaysia",
        "714" to "beIN Sports 3 Malaysia",
        "271" to "Canal+ MotoGP France",
        "273" to "Canal+ Formula 1",
        "121" to "Canal+ France",
        "122" to "Canal+ Sport France",
        "463" to "Canal+ Foot France",
        "464" to "Canal+ Sport360",
        "119" to "RMC Sport 1 France",
        "120" to "RMC Sport 2 France",
        "960" to "DAZN Ligue 1 France",
        "772" to "Eurosport 1 France",
        "773" to "Eurosport 2 France",
        "84" to "Movistar Laliga",
        "435" to "Movistar Liga de Campeones",
        "436" to "Movistar Deportes Spain",
        "438" to "Movistar Deportes 2 Spain",
        "526" to "Movistar Deportes 3 Spain",
        "527" to "Movistar Deportes 4 Spain",
        "445" to "DAZN 1 Spain",
        "446" to "DAZN 2 Spain",
        "447" to "DAZN 3 Spain",
        "448" to "DAZN 4 Spain",
        "537" to "DAZN F1 ES",
        "538" to "DAZN LaLiga",
        "524" to "EuroSport 1 Spain",
        "525" to "EuroSport 2 Spain",
        "530" to "GOL PLAY Spain",
        "529" to "Teledeporte Spain",
        "523" to "Real Madrid TV Spain",
        "522" to "Barca TV Spain",
        "240" to "Sky Sports 1 DE",
        "241" to "Sky Sports 2 DE",
        "558" to "Sky Sport Bundesliga 1 HD",
        "946" to "Sky Sport Bundesliga 2",
        "947" to "Sky Sport Bundesliga 3",
        "948" to "Sky Sport Bundesliga 4",
        "949" to "Sky Sport Bundesliga 5",
        "274" to "Sky Sports F1 DE",
        "426" to "DAZN 1 Bar DE",
        "427" to "DAZN 2 Bar DE",
        "641" to "Sport 1 Germany",
        "571" to "SportDigital Fussball",
        "460" to "Sky Sport MAX Italy",
        "461" to "Sky Sport UNO Italy",
        "462" to "Sky Sport Arena Italy",
        "869" to "Sky Sport 24 Italy",
        "870" to "Sky Sport Calcio Italy",
        "871" to "Sky Calcio 1 Italy",
        "872" to "Sky Calcio 2 Italy",
        "873" to "Sky Calcio 3 Italy",
        "874" to "Sky Calcio 4 Italy",
        "875" to "Sky Sport Basket Italy",
        "577" to "Sky Sport F1 Italy",
        "575" to "Sky Sport MotoGP Italy",
        "878" to "EuroSport 1 Italy",
        "879" to "EuroSport 2 Italy",
        "877" to "DAZN ZONA Italy",
        "882" to "Rai Sport Italy",
        "48" to "Canal+ Sport Poland",
        "73" to "Canal+ Sport 2 Poland",
        "259" to "Canal+ Sport 3 Poland",
        "983" to "Canal+ Extra 1-7 Poland",
        "47" to "Polsat Sport Poland",
        "50" to "Polsat Sport 2 Poland",
        "129" to "Polsat Sport 3 Poland",
        "991" to "Polsat Sport Premium 1",
        "992" to "Polsat Sport Premium 2",
        "993" to "Polsat Sport Extra 1",
        "994" to "Polsat Sport Extra 2",
        "995" to "Polsat Sport Extra 3",
        "996" to "Polsat Sport Extra 4",
        "997" to "Polsat Sport Fight",
        "998" to "Polsat Sport NEWS",
        "71" to "Eleven Sports 1 Poland",
        "72" to "Eleven Sports 2 Poland",
        "428" to "Eleven Sports 3 Poland",
        "999" to "Eleven Sports 4 Poland",
        "57" to "EuroSport 1 Poland",
        "58" to "EuroSport 2 Poland",
        "128" to "TVP Sport Poland",
        "49" to "Sport TV1 Portugal",
        "74" to "Sport TV2 Portugal",
        "454" to "Sport TV3 Portugal",
        "289" to "Sport TV4 Portugal",
        "290" to "Sport TV5 Portugal",
        "291" to "Sport TV6 Portugal",
        "455" to "Eleven Sports 1 Portugal",
        "456" to "Eleven Sports 2 Portugal",
        "457" to "Eleven Sports 3 Portugal",
        "458" to "Eleven Sports 4 Portugal",
        "459" to "Eleven Sports 5 Portugal",
        "380" to "Benfica TV PT",
        "41" to "EuroSport 1 Greece",
        "42" to "EuroSport 2 Greece",
        "631" to "Nova Sports 1 Greece",
        "632" to "Nova Sports 2 Greece",
        "633" to "Nova Sports 3 Greece",
        "634" to "Nova Sports 4 Greece",
        "635" to "Nova Sports 5 Greece",
        "636" to "Nova Sports 6 Greece",
        "599" to "Nova Sports Premier League",
        "622" to "Cosmote Sport 1 HD",
        "623" to "Cosmote Sport 2 HD",
        "624" to "Cosmote Sport 3 HD",
        "625" to "Cosmote Sport 4 HD",
        "626" to "Cosmote Sport 5 HD",
        "627" to "Cosmote Sport 6 HD",
        "628" to "Cosmote Sport 7 HD",
        "629" to "Cosmote Sport 8 HD",
        "630" to "Cosmote Sport 9 HD",
        "400" to "Digi Sport 1 Romania",
        "401" to "Digi Sport 2 Romania",
        "402" to "Digi Sport 3 Romania",
        "403" to "Digi Sport 4 Romania",
        "439" to "Orange Sport 1 Romania",
        "440" to "Orange Sport 2 Romania",
        "441" to "Orange Sport 3 Romania",
        "442" to "Orange Sport 4 Romania",
        "583" to "Prima Sport 1",
        "584" to "Prima Sport 2",
        "585" to "Prima Sport 3",
        "586" to "Prima Sport 4",
        "134" to "Arena Sport 1 Premium",
        "135" to "Arena Sport 2 Premium",
        "429" to "Arena Sport 1 Serbia",
        "430" to "Arena Sport 2 Serbia",
        "431" to "Arena Sport 3 Serbia",
        "581" to "Arena Sport 4 Serbia",
        "940" to "Arena Sport 5-10 Serbia",
        "432" to "Arena Sport 1 Croatia",
        "433" to "Arena Sport 2 Croatia",
        "434" to "Arena Sport 3 Croatia",
        "580" to "Arena Sport 4 Croatia",
        "579" to "Arena Sport 1 BiH",
        "101" to "Sport Klub 1 Croatia",
        "102" to "Sport Klub 2 Croatia",
        "103" to "Sport Klub 3 Croatia",
        "104" to "Sport Klub 4 Croatia",
        "582" to "Nova Sport Serbia",
        "779" to "Max Sport 1 Croatia",
        "780" to "Max Sport 2 Croatia",
        "465" to "Diema Sport Bulgaria",
        "466" to "Diema Sport 2 Bulgaria",
        "467" to "Diema Sport 3 Bulgaria",
        "468" to "Nova Sport Bulgaria",
        "472" to "Max Sport 1 Bulgaria",
        "473" to "Max Sport 2 Bulgaria",
        "474" to "Max Sport 3 Bulgaria",
        "475" to "Max Sport 4 Bulgaria",
        "600" to "Abu Dhabi Sports 1 UAE",
        "601" to "Abu Dhabi Sports 2 UAE",
        "604" to "Dubai Sports 1 UAE",
        "605" to "Dubai Sports 2 UAE",
        "606" to "Dubai Sports 3 UAE",
        "781" to "Alkass One",
        "782" to "Alkass Two",
        "783" to "Alkass Three",
        "784" to "Alkass Four",
        "611" to "OnTime Sports",
        "614" to "SSC Sport 1",
        "615" to "SSC Sport 2",
        "616" to "SSC Sport 3",
        "617" to "SSC Sport 4",
        "618" to "SSC Sport 5",
        "619" to "SSC Sport Extra 1",
        "620" to "SSC Sport Extra 2",
        "621" to "SSC Sport Extra 3",
        "412" to "SuperSport Grandstand",
        "413" to "SuperSport PSL",
        "414" to "SuperSport Premier League",
        "415" to "SuperSport LaLiga",
        "416" to "SuperSport Variety 1",
        "417" to "SuperSport Variety 2",
        "418" to "SuperSport Variety 3",
        "419" to "SuperSport Variety 4",
        "420" to "SuperSport Action",
        "421" to "SuperSport Rugby",
        "422" to "SuperSport Golf",
        "423" to "SuperSport Tennis",
        "424" to "SuperSport Motorsport",
        "56" to "Supersport Football",
        "368" to "SuperSport Cricket",
        "123" to "Astro SuperSport 1",
        "124" to "Astro SuperSport 2",
        "125" to "Astro SuperSport 3",
        "126" to "Astro SuperSport 4",
        "267" to "Star Sports 1 IN",
        "268" to "Star Sports Hindi IN",
        "885" to "SONY TEN 1",
        "886" to "SONY TEN 2",
        "887" to "SONY TEN 3",
        "450" to "PTV Sports",
        "269" to "A Sport PK",
        "741" to "Ten Sports PK",
        "270" to "T Sports BD",
        "346" to "Willow Cricket",
        "598" to "Willow 2 Cricket",
        "369" to "Fox Cricket",
        "111" to "TSN1",
        "112" to "TSN2",
        "113" to "TSN3",
        "114" to "TSN4",
        "115" to "TSN5",
        "406" to "Sportsnet Ontario",
        "407" to "Sportsnet West",
        "408" to "Sportsnet East",
        "409" to "Sportsnet 360",
        "410" to "Sportsnet World",
        "411" to "Sportsnet One",
        "839" to "RDS CA",
        "840" to "RDS 2 CA",
        "833" to "TVA Sports",
        "834" to "TVA Sports 2",
        "78" to "SporTV Brasil",
        "79" to "SporTV2 Brasil",
        "80" to "SporTV3 Brasil",
        "81" to "ESPN Brasil",
        "82" to "ESPN2 Brasil",
        "83" to "ESPN3 Brasil",
        "149" to "ESPN Argentina",
        "150" to "ESPN2 Argentina",
        "787" to "Fox Sports Argentina",
        "388" to "TNT Sports Argentina",
        "746" to "TyC Sports Argentina",
        "925" to "ESPN 1 MX",
        "926" to "ESPN 2 MX",
        "929" to "Fox Sports 1 MX",
        "930" to "Fox Sports 2 MX",
        "933" to "Claro Sports MX",
        "935" to "TUDN MX",
        "588" to "Sky Sport 1 NZ",
        "589" to "Sky Sport 2 NZ",
        "590" to "Sky Sport 3 NZ",
        "591" to "Sky Sport 4 NZ",
        "592" to "Sky Sport 5 NZ",
        "820" to "FOX Sports 502 AU",
        "821" to "FOX Sports 503 AU",
        "822" to "FOX Sports 504 AU",
        "823" to "FOX Sports 505 AU",
        "231" to "Eurosport 1 SW",
        "232" to "Eurosport 2 SW",
        "703" to "TV4 Sport Live 1",
        "704" to "TV4 Sport Live 2",
        "705" to "TV4 Sport Live 3",
        "706" to "TV4 Sport Live 4",
        "707" to "TV4 Sportkanalen",
        "808" to "TV2 Sport X Denmark",
        "809" to "TV3 Sport Denmark",
        "810" to "TV2 Sport Denmark",
        "379" to "ESPN 1 NL",
        "386" to "ESPN 2 NL",
        "888" to "ESPN 3 NL",
        "393" to "Ziggo Sport NL",
        "398" to "Ziggo Sport 2 NL",
        "919" to "Ziggo Sport 3 NL",
        "396" to "Ziggo Sport 4 NL",
        "383" to "Ziggo Sport 5 NL",
        "901" to "Ziggo Sport 6 NL",
        "140" to "Sport 1 Israel",
        "141" to "Sport 2 Israel",
        "142" to "Sport 3 Israel",
        "143" to "Sport 4 Israel",
        "144" to "Sport 5 Israel",
        "145" to "Sport 5 PLUS Israel",
        "146" to "Sport 5 Live Israel",
        "147" to "Sport 5 Star Israel",
        "148" to "Sport 5 Gold Israel",
        "136" to "Match Football 1 Russia",
        "137" to "Match Football 2 Russia",
        "138" to "Match Football 3 Russia",
        "127" to "Match TV Russia",
        "1011" to "A Spor Turkey",
        "889" to "TRT Spor TR",
        "911" to "Cytavision Sports 1 Cyprus",
        "912" to "Cytavision Sports 2 Cyprus",
        "913" to "Cytavision Sports 3 Cyprus",
        "1021" to "Nova Sport 1 CZ",
        "1022" to "Nova Sport 2 CZ",
        "1023" to "Nova Sport 3 CZ",
        "1024" to "Nova Sport 4 CZ",
        "1033" to "CT Sport CZ",
        "1020" to "Canal+ Sport CZ",
        "1030" to "Premier Sport 1 CZ",
        "1031" to "Premier Sport 2 CZ",
        "1052" to "JOJ Spor SK",
        "1063" to "Canal+ Sport SK",
        "356" to "BBC One UK",
        "357" to "BBC Two UK",
        "358" to "BBC Three UK",
        "359" to "BBC Four UK",
        "349" to "BBC News Channel HD",
        "350" to "ITV 1 UK",
        "351" to "ITV 2 UK",
        "352" to "ITV 3 UK",
        "353" to "ITV 4 UK",
        "354" to "Channel 4 UK",
        "355" to "Channel 5 UK",
        "361" to "Sky Witness HD",
        "362" to "Sky Atlantic",
        "363" to "E4 Channel",
        "348" to "Dave",
        "687" to "Gold UK",
        "688" to "Film4 UK",
        "682" to "Sky Showcase UK",
        "683" to "Sky Arts UK",
        "684" to "Sky Comedy UK",
        "685" to "Sky Crime",
        "686" to "Sky History",
        "708" to "Sky MAX UK",
        "364" to "RTE 1",
        "365" to "RTE 2",
        "51" to "ABC USA",
        "52" to "CBS USA",
        "53" to "NBC USA",
        "54" to "FOX USA",
        "345" to "CNN USA",
        "327" to "MSNBC",
        "347" to "Fox News",
        "309" to "CNBC USA",
        "336" to "TBS USA",
        "338" to "TNT USA",
        "303" to "AMC USA",
        "302" to "A&E USA",
        "317" to "FX USA",
        "307" to "Bravo USA",
        "315" to "E! Entertainment",
        "326" to "Lifetime Network",
        "320" to "Hallmark Channel",
        "382" to "HGTV",
        "384" to "The Food Network",
        "337" to "TLC",
        "313" to "Discovery Channel",
        "304" to "Animal Planet",
        "322" to "History USA",
        "328" to "National Geographic",
        "294" to "Science Channel",
        "373" to "SYFY USA",
        "339" to "Cartoon Network",
        "312" to "Disney Channel",
        "330" to "NICK",
        "310" to "Comedy Central",
        "371" to "MTV USA",
        "344" to "VH1 USA",
        "321" to "HBO USA",
        "689" to "HBO2 USA",
        "374" to "Cinemax USA",
        "333" to "Showtime USA",
        "335" to "Starz",
        "970" to "Starz Cinema",
        "975" to "Starz Encore",
        "334" to "Paramount Network",
        "671" to "Sky Cinema Premiere UK",
        "672" to "Sky Cinema Select UK",
        "673" to "Sky Cinema Hits UK",
        "677" to "Sky Cinema Action UK",
        "678" to "Sky Cinema Comedy UK",
        "680" to "Sky Cinema Drama UK",
        "860" to "Sky Cinema Uno Italy",
        "861" to "Sky Cinema Action Italy",
        "862" to "Sky Cinema Comedy Italy",
        "864" to "Sky Cinema Romance Italy",
        "469" to "TF1 France",
        "470" to "M6 France",
        "950" to "France 2",
        "951" to "France 3",
        "952" to "France 4",
        "953" to "France 5",
        "956" to "C8 France",
        "957" to "BFM TV France",
        "958" to "Arte France",
        "850" to "Rai 1 Italy",
        "851" to "Rai 2 Italy",
        "852" to "Rai 3 Italy",
        "854" to "Italia 1 Italy",
        "855" to "La7 Italy",
        "881" to "Sky UNO Italy",
        "533" to "TVE La 1 Spain",
        "532" to "Telecinco Spain",
        "531" to "Antena 3 Spain",
        "727" to "ZDF DE",
        "740" to "RTL DE",
        "729" to "SAT.1 DE",
        "730" to "ProSieben DE",
        "719" to "RTP 1 Portugal",
        "720" to "RTP 2 Portugal",
        "722" to "SIC Portugal",
        "723" to "TVI Portugal",
        "479" to "bTV Bulgaria",
        "480" to "Nova TV Bulgaria",
        "476" to "BNT 1 Bulgaria",
        "602" to "CTV Canada",
        "832" to "CBC CA",
        "836" to "Global CA",
        "1000" to "ATV Turkey",
        "1001" to "Kanal D Turkey",
        "1002" to "Show TV Turkey",
        "801" to "DR1 Denmark",
        "802" to "DR2 Denmark",
        "817" to "TV2 Denmark",
        "390" to "RTL7 Netherland",
        "378" to "Veronica NL",
        "546" to "Channel 9 Israel",
        "549" to "Channel 12 Israel",
        "1034" to "Nova HD CZ",
        "1035" to "CT1 HD CZ",
        "1050" to "JOJ SK",
        "760" to "Globo SP",
        "761" to "Globo RIO",
        "934" to "Azteca Uno MX",
        "924" to "Las Estrellas",
        "843" to "Prima TV RO"
    )

    private val logoFiles = mapOf(
        "31" to "tnt_sports_1_uk.png",
        "32" to "tnt_sports_2_uk.png",
        "33" to "tnt_sports_3_uk.png",
        "34" to "tnt_sports_4_uk.png",
        "35" to "sky_sports_football_uk.png",
        "36" to "sky_sports_plus.png",
        "37" to "sky_sports_action_uk.png",
        "38" to "sky_sports_main_event.png",
        "46" to "sky_sports_tennis_uk.png",
        "130" to "sky_sports_premier_league.png",
        "60" to "sky_sports_f1_uk.png",
        "65" to "sky_sports_cricket.png",
        "70" to "sky_sports_golf_uk.png",
        "366" to "sky_sports_news_uk.png",
        "449" to "sky_sports_mix_uk.png",
        "554" to "sky_sports_racing_uk.png",
        "276" to "lalagatv_uk.png",
        "230" to "dazn_1_uk.png",
        "451" to "viaplay_sports_1_uk.png",
        "550" to "viaplay_sports_2_uk.png",
        "377" to "mutv_uk.png",
        "826" to "liverpool_tv_lfc_tv.png",
        "771" to "premier_sports_ireland_1.png",
        "799" to "premier_sports_ireland_2.png",
        "44" to "espn_usa.png",
        "45" to "espn2_usa.png",
        "316" to "espnu_usa.png",
        "288" to "espnews.png",
        "375" to "espn_deportes.png",
        "39" to "fox_sports_1_usa.png",
        "758" to "fox_sports_2_usa.png",
        "756" to "fox_soccer_plus.png",
        "308" to "cbs_sports_network.png",
        "910" to "cbs_sports_golazo.png",
        "405" to "nfl_network.png",
        "667" to "nfl_redzone.png",
        "404" to "nba_tv_usa.png",
        "399" to "mlb_network_usa.png",
        "663" to "nhl_network_usa.png",
        "318" to "golf_channel_usa.png",
        "40" to "tennis_channel.png",
        "425" to "bein_sports_usa.png",
        "385" to "sec_network_usa.png",
        "664" to "acc_network_usa.png",
        "397" to "big_ten_network.png",
        "66" to "tudn_usa.png",
        "376" to "wwe_network.png",
        "757" to "fight_network.png",
        "43" to "pdc_tv.png",
        "765" to "msg_usa.png",
        "759" to "sportsnet_new_york_sny.png",
        "762" to "nesn_usa.png",
        "763" to "yes_network_usa.png",
        "770" to "marquee_sports_network.png",
        "776" to "chicago_sports_network.png",
        "777" to "nbc_sports_philadelphia.png",
        "921" to "space_city_home_network.png",
        "920" to "root_sports_northwest.png",
        "982" to "spectrum_sportsnet_usa.png",
        "764" to "spectrum_sportsnet_la.png",
        "890" to "fanduel_sports_az.png",
        "891" to "fanduel_sports_detroit.png",
        "892" to "fanduel_sports_florida.png",
        "893" to "fanduel_sports_great_lakes.png",
        "894" to "fanduel_sports_indiana.png",
        "895" to "fanduel_sports_kansas_city.png",
        "896" to "fanduel_sports_midwest.png",
        "897" to "fanduel_sports_new_orleans.png",
        "898" to "fanduel_sports_north.png",
        "899" to "fanduel_sports_ohio.png",
        "900" to "fanduel_sports_oklahoma.png",
        "902" to "fanduel_sports_socal.png",
        "903" to "fanduel_sports_south.png",
        "904" to "fanduel_sports_southeast.png",
        "905" to "fanduel_sports_sun.png",
        "906" to "fanduel_sports_west.png",
        "907" to "fanduel_sports_wisconsin.png",
        "61" to "bein_sports_mena_english_1.png",
        "90" to "bein_sports_mena_english_2.png",
        "91" to "bein_sports_1_arabic.png",
        "92" to "bein_sports_2_arabic.png",
        "93" to "bein_sports_3_arabic.png",
        "94" to "bein_sports_4_arabic.png",
        "95" to "bein_sports_5_arabic.png",
        "96" to "bein_sports_6_arabic.png",
        "97" to "bein_sports_7_arabic.png",
        "98" to "bein_sports_8_arabic.png",
        "99" to "bein_sports_9_arabic.png",
        "100" to "bein_sports_xtra_1.png",
        "494" to "bein_sports_max_4_france.png",
        "495" to "bein_sports_max_5_france.png",
        "496" to "bein_sports_max_6_france.png",
        "497" to "bein_sports_max_7_france.png",
        "498" to "bein_sports_max_8_france.png",
        "499" to "bein_sports_max_9_france.png",
        "500" to "bein_sports_max_10_france.png",
        "116" to "bein_sports_1_france.png",
        "117" to "bein_sports_2_france.png",
        "118" to "bein_sports_3_france.png",
        "62" to "bein_sports_1_turkey.png",
        "63" to "bein_sports_2_turkey.png",
        "64" to "bein_sports_3_turkey.png",
        "67" to "bein_sports_4_turkey.png",
        "1010" to "bein_sports_5_turkey.png",
        "578" to "bein_sports_hd_qatar.png",
        "372" to "bein_sports_en_espanol.png",
        "491" to "bein_sports_australia_1.png",
        "492" to "bein_sports_australia_2.png",
        "493" to "bein_sports_australia_3.png",
        "712" to "bein_sports_1_malaysia.png",
        "713" to "bein_sports_2_malaysia.png",
        "714" to "bein_sports_3_malaysia.png",
        "271" to "canal_motogp_france.png",
        "273" to "canal_formula_1.png",
        "121" to "canal_plus_france.png",
        "122" to "canal_sport_france.png",
        "463" to "canal_foot_france.png",
        "464" to "canal_sport360.png",
        "119" to "rmc_sport_1_france.png",
        "120" to "rmc_sport_2_france.png",
        "960" to "dazn_ligue_1_france.png",
        "772" to "eurosport_1_france.png",
        "773" to "eurosport_2_france.png",
        "84" to "movistar_laliga.png",
        "435" to "movistar_liga_de_campeones.png",
        "436" to "movistar_deportes_spain.png",
        "438" to "movistar_deportes_2_spain.png",
        "526" to "movistar_deportes_3_spain.png",
        "527" to "movistar_deportes_4_spain.png",
        "445" to "dazn_1_spain.png",
        "446" to "dazn_2_spain.png",
        "447" to "dazn_3_spain.png",
        "448" to "dazn_4_spain.png",
        "537" to "dazn_f1_es.png",
        "538" to "dazn_laliga.png",
        "524" to "eurosport_1_spain.png",
        "525" to "eurosport_2_spain.png",
        "530" to "gol_play_spain.png",
        "529" to "teledeporte_spain.png",
        "523" to "real_madrid_tv_spain.png",
        "522" to "barca_tv_spain.png",
        "240" to "sky_sports_1_de.png",
        "241" to "sky_sports_2_de.png",
        "558" to "sky_sport_bundesliga_1_hd.png",
        "946" to "sky_sport_bundesliga_2.png",
        "947" to "sky_sport_bundesliga_3.png",
        "948" to "sky_sport_bundesliga_4.png",
        "949" to "sky_sport_bundesliga_5.png",
        "274" to "sky_sports_f1_de.png",
        "426" to "dazn_1_bar_de.png",
        "427" to "dazn_2_bar_de.png",
        "641" to "sport_1_germany.png",
        "571" to "sportdigital_fussball.png",
        "460" to "sky_sport_max_italy.png",
        "461" to "sky_sport_uno_italy.png",
        "462" to "sky_sport_arena_italy.png",
        "869" to "sky_sport_24_italy.png",
        "870" to "sky_sport_calcio_italy.png",
        "871" to "sky_calcio_1_italy.png",
        "872" to "sky_calcio_2_italy.png",
        "873" to "sky_calcio_3_italy.png",
        "874" to "sky_calcio_4_italy.png",
        "875" to "sky_sport_basket_italy.png",
        "577" to "sky_sport_f1_italy.png",
        "575" to "sky_sport_motogp_italy.png",
        "878" to "eurosport_1_italy.png",
        "879" to "eurosport_2_italy.png",
        "877" to "dazn_zona_italy.png",
        "882" to "rai_sport_italy.png",
        "48" to "canal_sport_poland.png",
        "73" to "canal_sport_2_poland.png",
        "259" to "canal_sport_3_poland.png",
        "983" to "canal_extra_1_7_poland.png",
        "47" to "polsat_sport_poland.png",
        "50" to "polsat_sport_2_poland.png",
        "129" to "polsat_sport_3_poland.png",
        "991" to "polsat_sport_premium_1.png",
        "992" to "polsat_sport_premium_2.png",
        "993" to "polsat_sport_extra_1.png",
        "994" to "polsat_sport_extra_2.png",
        "995" to "polsat_sport_extra_3.png",
        "996" to "polsat_sport_extra_4.png",
        "997" to "polsat_sport_fight.png",
        "998" to "polsat_sport_news.png",
        "71" to "eleven_sports_1_poland.png",
        "72" to "eleven_sports_2_poland.png",
        "428" to "eleven_sports_3_poland.png",
        "999" to "eleven_sports_4_poland.png",
        "57" to "eurosport_1_poland.png",
        "58" to "eurosport_2_poland.png",
        "128" to "tvp_sport_poland.png",
        "49" to "sport_tv1_portugal.png",
        "74" to "sport_tv2_portugal.png",
        "454" to "sport_tv3_portugal.png",
        "289" to "sport_tv4_portugal.png",
        "290" to "sport_tv5_portugal.png",
        "291" to "sport_tv6_portugal.png",
        "455" to "eleven_sports_1_portugal.png",
        "456" to "eleven_sports_2_portugal.png",
        "457" to "eleven_sports_3_portugal.png",
        "458" to "eleven_sports_4_portugal.png",
        "459" to "eleven_sports_5_portugal.png",
        "380" to "benfica_tv_pt.png",
        "41" to "eurosport_1_greece.png",
        "42" to "eurosport_2_greece.png",
        "631" to "nova_sports_1_greece.png",
        "632" to "nova_sports_2_greece.png",
        "633" to "nova_sports_3_greece.png",
        "634" to "nova_sports_4_greece.png",
        "635" to "nova_sports_5_greece.png",
        "636" to "nova_sports_6_greece.png",
        "599" to "nova_sports_premier_league.png",
        "622" to "cosmote_sport_1_hd.png",
        "623" to "cosmote_sport_2_hd.png",
        "624" to "cosmote_sport_3_hd.png",
        "625" to "cosmote_sport_4_hd.png",
        "626" to "cosmote_sport_5_hd.png",
        "627" to "cosmote_sport_6_hd.png",
        "628" to "cosmote_sport_7_hd.png",
        "629" to "cosmote_sport_8_hd.png",
        "630" to "cosmote_sport_9_hd.png",
        "400" to "digi_sport_1_romania.png",
        "401" to "digi_sport_2_romania.png",
        "402" to "digi_sport_3_romania.png",
        "403" to "digi_sport_4_romania.png",
        "439" to "orange_sport_1_romania.png",
        "440" to "orange_sport_2_romania.png",
        "441" to "orange_sport_3_romania.png",
        "442" to "orange_sport_4_romania.png",
        "583" to "prima_sport_1.png",
        "584" to "prima_sport_2.png",
        "585" to "prima_sport_3.png",
        "586" to "prima_sport_4.png",
        "134" to "arena_sport_1_premium.png",
        "135" to "arena_sport_2_premium.png",
        "429" to "arena_sport_1_serbia.png",
        "430" to "arena_sport_2_serbia.png",
        "431" to "arena_sport_3_serbia.png",
        "581" to "arena_sport_4_serbia.png",
        "940" to "arena_sport_5_10_serbia.png",
        "432" to "arena_sport_1_croatia.png",
        "433" to "arena_sport_2_croatia.png",
        "434" to "arena_sport_3_croatia.png",
        "580" to "arena_sport_4_croatia.png",
        "579" to "arena_sport_1_bih.png",
        "101" to "sport_klub_1_croatia.png",
        "102" to "sport_klub_2_croatia.png",
        "103" to "sport_klub_3_croatia.png",
        "104" to "sport_klub_4_croatia.png",
        "582" to "nova_sport_serbia.png",
        "779" to "max_sport_1_croatia.png",
        "780" to "max_sport_2_croatia.png",
        "465" to "diema_sport_bulgaria.png",
        "466" to "diema_sport_2_bulgaria.png",
        "467" to "diema_sport_3_bulgaria.png",
        "468" to "nova_sport_bulgaria.png",
        "472" to "max_sport_1_bulgaria.png",
        "473" to "max_sport_2_bulgaria.png",
        "474" to "max_sport_3_bulgaria.png",
        "475" to "max_sport_4_bulgaria.png",
        "600" to "abu_dhabi_sports_1_uae.png",
        "601" to "abu_dhabi_sports_2_uae.png",
        "604" to "dubai_sports_1_uae.png",
        "605" to "dubai_sports_2_uae.png",
        "606" to "dubai_sports_3_uae.png",
        "781" to "alkass_one.png",
        "782" to "alkass_two.png",
        "783" to "alkass_three.png",
        "784" to "alkass_four.png",
        "611" to "ontime_sports.png",
        "614" to "ssc_sport_1.png",
        "615" to "ssc_sport_2.png",
        "616" to "ssc_sport_3.png",
        "617" to "ssc_sport_4.png",
        "618" to "ssc_sport_5.png",
        "619" to "ssc_sport_extra_1.png",
        "620" to "ssc_sport_extra_2.png",
        "621" to "ssc_sport_extra_3.png",
        "412" to "supersport_grandstand.png",
        "413" to "supersport_psl.png",
        "414" to "supersport_premier_league.png",
        "415" to "supersport_laliga.png",
        "416" to "supersport_variety_1.png",
        "417" to "supersport_variety_2.png",
        "418" to "supersport_variety_3.png",
        "419" to "supersport_variety_4.png",
        "420" to "supersport_action.png",
        "421" to "supersport_rugby.png",
        "422" to "supersport_golf.png",
        "423" to "supersport_tennis.png",
        "424" to "supersport_motorsport.png",
        "56" to "supersport_football.png",
        "368" to "supersport_cricket.png",
        "123" to "astro_supersport_1.png",
        "124" to "astro_supersport_2.png",
        "125" to "astro_supersport_3.png",
        "126" to "astro_supersport_4.png",
        "267" to "star_sports_1_in.png",
        "268" to "star_sports_hindi_in.png",
        "885" to "sony_ten_1.png",
        "886" to "sony_ten_2.png",
        "887" to "sony_ten_3.png",
        "450" to "ptv_sports.png",
        "269" to "a_sport_pk.png",
        "741" to "ten_sports_pk.png",
        "270" to "t_sports_bd.png",
        "346" to "willow_cricket.png",
        "598" to "willow_2_cricket.png",
        "369" to "fox_cricket.png",
        "111" to "tsn1.png",
        "112" to "tsn2.png",
        "113" to "tsn3.png",
        "114" to "tsn4.png",
        "115" to "tsn5.png",
        "406" to "sportsnet_ontario.png",
        "407" to "sportsnet_west.png",
        "408" to "sportsnet_east.png",
        "409" to "sportsnet_360.png",
        "410" to "sportsnet_world.png",
        "411" to "sportsnet_one.png",
        "839" to "rds_ca.png",
        "840" to "rds_2_ca.png",
        "833" to "tva_sports.png",
        "834" to "tva_sports_2.png",
        "78" to "sportv_brasil.png",
        "79" to "sportv2_brasil.png",
        "80" to "sportv3_brasil.png",
        "81" to "espn_brasil.png",
        "82" to "espn2_brasil.png",
        "83" to "espn3_brasil.png",
        "149" to "espn_argentina.png",
        "150" to "espn2_argentina.png",
        "787" to "fox_sports_argentina.png",
        "388" to "tnt_sports_argentina.png",
        "746" to "tyc_sports_argentina.png",
        "925" to "espn_1_mx.png",
        "926" to "espn_2_mx.png",
        "929" to "fox_sports_1_mx.png",
        "930" to "fox_sports_2_mx.png",
        "933" to "claro_sports_mx.png",
        "935" to "tudn_mx.png",
        "588" to "sky_sport_1_nz.png",
        "589" to "sky_sport_2_nz.png",
        "590" to "sky_sport_3_nz.png",
        "591" to "sky_sport_4_nz.png",
        "592" to "sky_sport_5_nz.png",
        "820" to "fox_sports_502_au.png",
        "821" to "fox_sports_503_au.png",
        "822" to "fox_sports_504_au.png",
        "823" to "fox_sports_505_au.png",
        "231" to "eurosport_1_sw.png",
        "232" to "eurosport_2_sw.png",
        "703" to "tv4_sport_live_1.png",
        "704" to "tv4_sport_live_2.png",
        "705" to "tv4_sport_live_3.png",
        "706" to "tv4_sport_live_4.png",
        "707" to "tv4_sportkanalen.png",
        "808" to "tv2_sport_x_denmark.png",
        "809" to "tv3_sport_denmark.png",
        "810" to "tv2_sport_denmark.png",
        "379" to "espn_1_nl.png",
        "386" to "espn_2_nl.png",
        "888" to "espn_3_nl.png",
        "393" to "ziggo_sport_nl.png",
        "398" to "ziggo_sport_2_nl.png",
        "919" to "ziggo_sport_3_nl.png",
        "396" to "ziggo_sport_4_nl.png",
        "383" to "ziggo_sport_5_nl.png",
        "901" to "ziggo_sport_6_nl.png",
        "140" to "sport_1_israel.png",
        "141" to "sport_2_israel.png",
        "142" to "sport_3_israel.png",
        "143" to "sport_4_israel.png",
        "144" to "sport_5_israel.png",
        "145" to "sport_5_plus_israel.png",
        "146" to "sport_5_live_israel.png",
        "147" to "sport_5_star_israel.png",
        "148" to "sport_5_gold_israel.png",
        "136" to "match_football_1_russia.png",
        "137" to "match_football_2_russia.png",
        "138" to "match_football_3_russia.png",
        "127" to "match_tv_russia.png",
        "1011" to "a_spor_turkey.png",
        "889" to "trt_spor_tr.png",
        "911" to "cytavision_sports_1_cyprus.png",
        "912" to "cytavision_sports_2_cyprus.png",
        "913" to "cytavision_sports_3_cyprus.png",
        "1021" to "nova_sport_1_cz.png",
        "1022" to "nova_sport_2_cz.png",
        "1023" to "nova_sport_3_cz.png",
        "1024" to "nova_sport_4_cz.png",
        "1033" to "ct_sport_cz.png",
        "1020" to "canal_sport_cz.png",
        "1030" to "premier_sport_1_cz.png",
        "1031" to "premier_sport_2_cz.png",
        "1052" to "joj_spor_sk.png",
        "1063" to "canal_sport_sk.png",
        "356" to "bbc_one_uk.png",
        "357" to "bbc_two_uk.png",
        "358" to "bbc_three_uk.png",
        "359" to "bbc_four_uk.png",
        "349" to "bbc_news_channel_hd.png",
        "350" to "itv_1_uk.png",
        "351" to "itv_2_uk.png",
        "352" to "itv_3_uk.png",
        "353" to "itv_4_uk.png",
        "354" to "channel_4_uk.png",
        "355" to "channel_5_uk.png",
        "361" to "sky_witness_hd.png",
        "362" to "sky_atlantic.png",
        "363" to "e4_channel.png",
        "348" to "dave.png",
        "687" to "gold_uk.png",
        "688" to "film4_uk.png",
        "682" to "sky_showcase_uk.png",
        "683" to "sky_arts_uk.png",
        "684" to "sky_comedy_uk.png",
        "685" to "sky_crime.png",
        "686" to "sky_history.png",
        "708" to "sky_max_uk.png",
        "364" to "rte_1.png",
        "365" to "rte_2.png",
        "51" to "abc_usa.png",
        "52" to "cbs_usa.png",
        "53" to "nbc_usa.png",
        "54" to "fox_usa.png",
        "345" to "cnn_usa.png",
        "327" to "msnbc.png",
        "347" to "fox_news.png",
        "309" to "cnbc_usa.png",
        "336" to "tbs_usa.png",
        "338" to "tnt_usa.png",
        "303" to "amc_usa.png",
        "302" to "a_e_usa.png",
        "317" to "fx_usa.png",
        "307" to "bravo_usa.png",
        "315" to "e_entertainment.png",
        "326" to "lifetime_network.png",
        "320" to "hallmark_channel.png",
        "382" to "hgtv.png",
        "384" to "the_food_network.png",
        "337" to "tlc.png",
        "313" to "discovery_channel.png",
        "304" to "animal_planet.png",
        "322" to "history_usa.png",
        "328" to "national_geographic.png",
        "294" to "science_channel.png",
        "373" to "syfy_usa.png",
        "339" to "cartoon_network.png",
        "312" to "disney_channel.png",
        "330" to "nick.png",
        "310" to "comedy_central.png",
        "371" to "mtv_usa.png",
        "344" to "vh1_usa.png",
        "321" to "hbo_usa.png",
        "689" to "hbo2_usa.png",
        "374" to "cinemax_usa.png",
        "333" to "showtime_usa.png",
        "335" to "starz.png",
        "970" to "starz_cinema.png",
        "975" to "starz_encore.png",
        "334" to "paramount_network.png",
        "671" to "sky_cinema_premiere_uk.png",
        "672" to "sky_cinema_select_uk.png",
        "673" to "sky_cinema_hits_uk.png",
        "677" to "sky_cinema_action_uk.png",
        "678" to "sky_cinema_comedy_uk.png",
        "680" to "sky_cinema_drama_uk.png",
        "860" to "sky_cinema_uno_italy.png",
        "861" to "sky_cinema_action_italy.png",
        "862" to "sky_cinema_comedy_italy.png",
        "864" to "sky_cinema_romance_italy.png",
        "469" to "tf1_france.png",
        "470" to "m6_france.png",
        "950" to "france_2.png",
        "951" to "france_3.png",
        "952" to "france_4.png",
        "953" to "france_5.png",
        "956" to "c8_france.png",
        "957" to "bfm_tv_france.png",
        "958" to "arte_france.png",
        "850" to "rai_1_italy.png",
        "851" to "rai_2_italy.png",
        "852" to "rai_3_italy.png",
        "854" to "italia_1_italy.png",
        "855" to "la7_italy.png",
        "881" to "sky_uno_italy.png",
        "533" to "tve_la_1_spain.png",
        "532" to "telecinco_spain.png",
        "531" to "antena_3_spain.png",
        "727" to "zdf_de.png",
        "740" to "rtl_de.png",
        "729" to "sat_1_de.png",
        "730" to "prosieben_de.png",
        "719" to "rtp_1_portugal.png",
        "720" to "rtp_2_portugal.png",
        "722" to "sic_portugal.png",
        "723" to "tvi_portugal.png",
        "479" to "btv_bulgaria.png",
        "480" to "nova_tv_bulgaria.png",
        "476" to "bnt_1_bulgaria.png",
        "602" to "ctv_canada.png",
        "832" to "cbc_ca.png",
        "836" to "global_ca.png",
        "1000" to "atv_turkey.png",
        "1001" to "kanal_d_turkey.png",
        "1002" to "show_tv_turkey.png",
        "801" to "dr1_denmark.png",
        "802" to "dr2_denmark.png",
        "817" to "tv2_denmark.png",
        "390" to "rtl7_netherland.png",
        "378" to "veronica_nl.png",
        "546" to "channel_9_israel.png",
        "549" to "channel_12_israel.png",
        "1034" to "nova_hd_cz.png",
        "1035" to "ct1_hd_cz.png",
        "1050" to "joj_sk.png",
        "760" to "globo_sp.png",
        "761" to "globo_rio.png",
        "934" to "azteca_uno_mx.png",
        "924" to "las_estrellas.png",
        "843" to "prima_tv_ro.png"
    )

    private val categoryMap = linkedMapOf(
        "Sports UK" to listOf("TNT Sports", "Sky Sports", "BBC Sport", "ITV", "Premier"),
        "Sports USA" to listOf("ESPN", "Fox Sports", "CBS Sports", "NBC Sports", "NFL", "NBA", "MLB", "NHL", "CBS Sports", "Golf", "Tennis"),
        "Sports beIN" to listOf("beIN"),
        "TV UK" to listOf("BBC One", "BBC Two", "ITV 1", "Channel 4", "Channel 5", "Sky", "UK"),
        "TV USA" to listOf("ABC USA", "CBS USA", "NBC USA", "FOX USA", "CNN", "HBO", "AMC", "USA Network"),
        "Other Channels" to emptyList<String>()
    )

    private fun getLogoUrl(id: String): String? {
        val fname = logoFiles[id] ?: return null
        // ใช้หลายโดเมน fallback เพราะ dlhd.pk บางทีล่ม
        return "https://dlhd.pk/logos/" + fname
    }

    override val mainPage = mainPageOf("channels" to "Live")

    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        val grouped = mutableMapOf<String, MutableList<SearchResponse>>()
        categoryMap.keys.forEach { grouped[it] = mutableListOf() }
        for ((id, title) in channelNames) {
            val item = newLiveSearchResponse(
                name = title,
                url = "$mainUrl/stream/stream-$id.php",
                type = TvType.Live
            ) {
                this.posterUrl = getLogoUrl(id)
            }
            var placed = false
            for ((cat, keys) in categoryMap) {
                if (cat == "Other Channels") continue
                if (keys.any { k -> title.contains(k, ignoreCase = true) }) {
                    grouped[cat]?.add(item); placed = true; break
                }
            }
            if (!placed) grouped["Other Channels"]?.add(item)
        }
        val lists = grouped.filter { it.value.isNotEmpty() }.map { (cat, items) ->
            HomePageList(cat, items.sortedBy { it.name }, false)
        }
        return newHomePageResponse(lists)
    }

    override suspend fun search(query: String): List<SearchResponse> {
        return channelNames.filter { it.value.contains(query, true) }.map { (id, title) ->
            newLiveSearchResponse(title, "$mainUrl/stream/stream-$id.php", TvType.Live) {
                this.posterUrl = getLogoUrl(id)
            }
        }
    }

    override suspend fun load(url: String): LoadResponse {
        val id = Regex("stream-(\\d+)").find(url)?.groupValues?.get(1) ?: "0"
        val title = channelNames[id] ?: "Channel $id"
        return newLiveStreamLoadResponse(name = title, url = url, dataUrl = url) {
            this.posterUrl = getLogoUrl(id)
        }
    }

    // แกะแบบใหม่รองรับ _econfig, epiembeds, atob 2 ชั้น
    private fun extractM3u8(html: String): String? {
        // 1) _econfig = atob(...)
        Regex("_econfig\\s*=\\s*JSON\\.parse\\(atob\\(['\"]([^'\"]+)['\"]\\)").findAll(html).forEach { m ->
            try {
                val json = String(Base64.decode(m.groupValues[1], Base64.DEFAULT))
                Regex("https?://[^\\s'\"<>]+\\.m3u8[^\\s'\"<>]+").find(json)?.let { return it.value }
                Regex("\"hls\"\\s*:\\s*\"([^\"]+)\"").find(json)?.let { return it.groupValues[1] }
            } catch (_:Exception) {}
        }
        // 2) atob ธรรมดา
        Regex("atob\\(['\"]([^'\"]+)['\"]\\)").findAll(html).forEach { m ->
            try {
                var d = String(Base64.decode(m.groupValues[1], Base64.DEFAULT))
                if (!d.contains("http") && d.length > 20) {
                    try { d = String(Base64.decode(d.trim(), Base64.DEFAULT)) } catch (_:Exception) {}
                }
                Regex("https?://[^\\s'\"<>]+\\.m3u8[^\\s'\"<>]+").find(d)?.let { return it.value }
            } catch (_:Exception) {}
        }
        // 3) ตรงๆ
        return Regex("https?://[^\\s'\"<>]+\\.m3u8[^\\s'\"<>]+").find(html)?.value
            ?: Regex("file:\\s*\"([^\"]+\\.m3u8[^\"]*)\"").find(html)?.groupValues?.get(1)
    }

    override suspend fun loadLinks(data: String, isCasting: Boolean, sub: (SubtitleFile)->Unit, cb: (ExtractorLink)->Unit): Boolean {
        val id = Regex("(\\d+)").find(data)?.value ?: return false
        // ลองทั้ง 6 server + หลายโดเมน
        val domains = listOf("https://dlive.sx", "https://dlhd.sx", "https://daddylivehd.sx")
        for (domain in domains) {
            for (folder in listOf("stream","cast","watch","plus","casting","player")) {
                val pageUrl = "$domain/$folder/stream-$id.php"
                try {
                    val html1 = app.get(pageUrl, headers = siteHeaders).text
                    if (html1.length < 500) continue
                    extractM3u8(html1)?.let { m3u8 ->
                        cb.invoke(newExtractorLink(name, "$name [$folder]", m3u8, ExtractorLinkType.M3U8) { this.referer = pageUrl; this.quality = Qualities.Unknown.value })
                        return true
                    }
                    val iframes = Regex("<iframe[^>]+src=['\"]([^'\"]+)['\"]").findAll(html1).map { it.groupValues[1] }.toList()
                    for (src in iframes) {
                        val iframeUrl = if (src.startsWith("http")) src else "$domain/${src.trimStart('/')}"
                        val html2 = app.get(iframeUrl, headers = siteHeaders + mapOf("Referer" to pageUrl)).text
                        extractM3u8(html2)?.let { m3u8 ->
                            cb.invoke(newExtractorLink(name, name, m3u8, ExtractorLinkType.M3U8) { this.referer = iframeUrl; this.quality = Qualities.Unknown.value })
                            return true
                        }
                        // iframe ชั้น 2
                        Regex("<iframe[^>]+src=['\"]([^'\"]+)['\"]").find(html2)?.let { inner ->
                            val innerSrc = inner.groupValues[1]
                            val innerUrl = if (innerSrc.startsWith("http")) innerSrc else "$domain/${innerSrc.trimStart('/')}"
                            val html3 = app.get(innerUrl, headers = siteHeaders + mapOf("Referer" to iframeUrl)).text
                            extractM3u8(html3)?.let { m3u8 ->
                                cb.invoke(newExtractorLink(name, name, m3u8, ExtractorLinkType.M3U8) { this.referer = innerUrl; this.quality = Qualities.Unknown.value })
                                return true
                            }
                        }
                    }
                } catch (_:Exception) {}
            }
        }
        return false
    }
}
